-- MySQL Script generated by MySQL Workbench
-- Wed Nov 25 14:44:18 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema substitution_aliments
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema substitution_aliments
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `substitution_aliments` DEFAULT CHARACTER SET utf8 ;
USE `substitution_aliments` ;

-- -----------------------------------------------------
-- Table `substitution_aliments`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `substitution_aliments`.`categories` ;

CREATE TABLE IF NOT EXISTS `substitution_aliments`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(70) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `substitution_aliments`.`aliments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `substitution_aliments`.`aliments` ;

CREATE TABLE IF NOT EXISTS `substitution_aliments`.`aliments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(500) NULL,
  `allergen` TEXT(2000) NULL,
  ` nutrition_grade` CHAR(1) NULL,
  `category` VARCHAR(500) NULL,
  `brand` VARCHAR(100) NULL,
  `country` VARCHAR(70) NULL,
  `weight_unit` VARCHAR(45) NULL,
  `energy` VARCHAR(45) NULL,
  `weight_value` VARCHAR(45) NULL,
  `categories_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_aliments_categories_idx` (`categories_id` ASC) VISIBLE,
  CONSTRAINT `fk_aliments_categories`
    FOREIGN KEY (`categories_id`)
    REFERENCES `substitution_aliments`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `substitution_aliments`.`aliments_substitues`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `substitution_aliments`.`aliments_substitues` ;

CREATE TABLE IF NOT EXISTS `substitution_aliments`.`aliments_substitues` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(500) NULL,
  `substitute_to` VARCHAR(500) NULL,
  `allergen` TEXT(2000) NULL,
  ` nutrition_grade` CHAR(1) NULL,
  `category` VARCHAR(500) NULL,
  `brand` VARCHAR(100) NULL,
  `country` VARCHAR(70) NULL,
  `weight_unit` VARCHAR(45) NULL,
  `energy` VARCHAR(45) NULL,
  `weight_value` VARCHAR(45) NULL,
  `aliment_substitue` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_aliments_substitues_aliments1_idx` (`aliment_substitue` ASC) VISIBLE,
  CONSTRAINT `fk_aliments_substitues_aliments1`
    FOREIGN KEY (`aliment_substitue`)
    REFERENCES `substitution_aliments`.`aliments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
